version: '3'
services:
#    upms1:
#        image: tomcat_wbm 
#        hostname: zheng_upms_1
#        volumes: 
#            - "/etc/localtime:/etc/localtime:ro" 
#            - "/home/containerd/wbm1/www/webserver/zheng-upms-server:/opt/www/webserver/zheng-upms-server"
#            - "/home/containerd/wbm1/tomcat/tomcat-upms-8800:/opt/tomcat/tomcat-upms-8800"
#            - "/home/containerd/wbm1/hosts:/etc/hosts"
#        ports:
#            - "8802:8800"
#        command: /preparation/start.sh 
#        environment:
#            SERVICE_PATH: "/opt/tomcat/tomcat-upms-8800"
#        deploy:
#            placement:
#                constraints: [node.hostname == wbm65]
#            resources:
#                limits:
#                    memory: 1G
#    rms:
#        image: tomcat_wbm
#        hostname: wbm_rms
#        volumes:
#            - "/etc/localtime:/etc/localtime:ro"
#            - "/home/containerd/wbm/www/webserver/wbm-rms-admin:/opt/www/webserver/wbm-rms-admin"
#            - "/home/containerd/wbm/tomcat/tomcat-rms-8806:/opt/tomcat/tomcat-rms-8806"
#            - "/home/containerd/wbm/hosts:/etc/hosts"
#        ports:
#            - "8806:8806"
#        command: /preparation/start.sh
#        environment:
#            SERVICE_PATH: "/opt/tomcat/tomcat-rms-8806"
#        deploy:
#            placement:
#                constraints: [node.hostname == wbm65]
#            resources:
#                limits:
#                    memory: 1G

    bi1:
        image: tomcat_wbm
        hostname: wbm_bi_1
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/home/containerd/wbm1/www/webserver/wbm-bi-admin:/opt/www/webserver/wbm-bi-admin"
            - "/home/containerd/wbm1/tomcat/tomcat-bi-8807:/opt/tomcat/tomcat-bi-8807"
            - "/home/containerd/wbm1/hosts:/etc/hosts"
        ports:
            - "8708:8807"
        command: /preparation/start.sh
        environment:
            SERVICE_PATH: "/opt/tomcat/tomcat-bi-8807"
        deploy:
            placement:
                constraints: [node.hostname == wbm65]
            resources:
                limits:
                    memory: 1G


#    redis2:
#        image: tomcat_wbm 
#        hostname: redis2
#        volumes:
#            - "/etc/localtime:/etc/localtime:ro"
#            - "/home/containerd/redis/redis_6380/config/redis.conf:/etc/redis/redis.conf:rw"
#            - "/home/containerd/redis/redis_6380/data:/var/lib/redis"
#            - "/home/containerd/redis/redis_6380/log:/var/log/redis"
#        ports:
#            - "16380:6379"
#        environment:
#            REDIS_ROLE: "slave"
#            MASTER_CONTAINER: "redis1"
#        command: /preparation/redis.sh
#        depends_on: 
#            - redis1
#        deploy:
#            placement:
#                constraints: [node.hostname == wbm84]
#            resources:
#                limits:
#                    memory: 500M
#    redis3:
#        image: 10.126.2.65:5000/ubuntu_16.04_ssh_redis
#        hostname: redis3
#        volumes:
#            - "/etc/localtime:/etc/localtime:ro"
#            - "/home/containerd/redis/redis_6381/config/redis.conf:/etc/redis/redis.conf:rw"
#            - "/home/containerd/redis/redis_6381/data:/var/lib/redis"
#            - "/home/containerd/redis/redis_6381/log:/var/log/redis"
#        ports:
#            - "6381:6379"
#        environment:
#            REDIS_ROLE: "slave"
#            MASTER_CONTAINER: "redis1"
#        command: /preparation/redis.sh
#        depends_on: 
#            - redis1


#networks:
#    ingress:
#        driver: bridge
