/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-11-29 02:20:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.manage.qy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class basCostConfigCreate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar", Long.valueOf(1541076044000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528799796000L));
    _jspx_dependants.put("jar:file:/opt/www/webserver/wbm-bi-admin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/opt/www/webserver/wbm-bi-admin/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/opt/www/webserver/wbm-bi-admin/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1539563356000L));
    _jspx_dependants.put("jar:file:/opt/www/webserver/wbm-bi-admin/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1539563356000L));
    _jspx_dependants.put("jar:file:/opt/www/webserver/wbm-bi-admin/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/shiro-web-1.3.2.jar", Long.valueOf(1528799788000L));
    _jspx_dependants.put("jar:file:/opt/www/webserver/wbm-bi-admin/WEB-INF/lib/shiro-web-1.3.2.jar!/META-INF/shiro.tld", Long.valueOf(1473414826000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/inc/head.jsp", out, true);
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html lang=\"zh-cn\">\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t<title>新增特殊项目</title>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/inc/head.jsp", out, true);
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"main\">\n");
      out.write("\t<form modelAttribute=\"basCostConfig\" method=\"post\">\n");
      out.write("\t\t<table class=\"table table-striped table-bordered table-hover \" id=\"editable\">\n");
      out.write("\t\t\t<thead>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<th>计算月份</th>\n");
      out.write("\t\t\t\t<th>明细标识</th>\n");
      out.write("\t\t\t\t<th nowrap>订单编号</th>\n");
      out.write("\t\t\t\t<th nowrap>项目编号</th>\n");
      out.write("\t\t\t\t<th nowrap=\"\">项目名称</th>\n");
      out.write("\t\t\t\t<th nowrap>人工成本<br>分类</th>\n");
      out.write("\t\t\t\t<th>核定人工成本</th>\n");
      out.write("\t\t\t\t<th style=\"width: 65px;\">核定项目管理人工成本</th>\n");
      out.write("\t\t\t\t<th style=\"width: 65px;\">核定风险及能力成本</th>\n");
      out.write("\t\t\t\t<th style=\"width: 65px;\">核定人工激励成本</th>\n");
      out.write("\t\t\t\t<th style=\"width: 65px;\">核定渠道管理激励成本</th>\n");
      out.write("\t\t\t\t<th>核定分包成本</th>\n");
      out.write("\t\t\t\t<th>核定托管成本</th>\n");
      out.write("\t\t\t\t<th>核定人工<br>-激励成本</th>\n");
      out.write("\t\t\t\t<th>核定托管<br>-管理成本</th>\n");
      out.write("\t\t\t\t<th>核定托管<br>-风险成本</th>\n");
      out.write("\t\t\t\t<th>支付日期</th>\n");
      out.write("\t\t\t\t<th>备注</th>\n");
      out.write("\t\t\t\t<th>操作</th>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t</thead>\n");
      out.write("\t\t\t<tbody>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td><input id=\"calcYf\" type=\"text\" name=\"calcYf\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.calcYf}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small form-control\" style=\"width: 80px;\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"pdId\" type=\"text\" name=\"pdId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.pdId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-medium\" style=\"direction:rtl;width: 122px;padding: 0px;display: inline\">\n");
      out.write("\t\t\t\t\t<a onclick=\"getRow(this);\" href=\"javascript:;\" title=\"获取\" data-toggle=\"tooltip\"><i class=\"glyphicon glyphicon-search\"></i></a>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td id=\"orderId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.orderId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t\t<td id=\"dcPrjId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.dcPrjId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t\t<td id=\"dcPrjName\" style=\"max-width: 100px;overflow:hidden;text-overflow:ellipsis;\" nowrap class=\"title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.dcPrjName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t\t<td id=\"costClassName\" style=\"max-width: 90px;overflow:hidden;text-overflow:ellipsis;\" nowrap class=\"title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.costClassName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t\t<td><input id=\"finalMancost\" type=\"text\" name=\"finalMancost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalMancost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"finalPmmancost\" type=\"text\" name=\"finalPmmancost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalPmmancost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\" style=\"width: 65px;\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"finalRiskabilitycost\" type=\"text\" name=\"finalRiskabilitycost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalRiskabilitycost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\" style=\"width: 65px;\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"finalUrgecost\" type=\"text\" name=\"finalUrgecost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalUrgecost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\" style=\"width: 65px;\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"finalSuburgecost\" type=\"text\" name=\"finalSuburgecost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalSuburgecost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\" style=\"width: 65px;\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"finalSubcost\" type=\"text\" name=\"finalSubcost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalSubcost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"finalHostcost\" type=\"text\" name=\"finalHostcost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalHostcost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"finalManurgecost\" type=\"text\" name=\"finalManurgecost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalManurgecost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"finalHostmancost\" type=\"text\" name=\"finalHostcost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalHostmancost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"finalSubriskcost\" type=\"text\" name=\"finalHostcost\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalSubriskcost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"payDate\" type=\"text\" name=\"payDate\" value=\"");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"input-small form-control\" style=\"width: 100px;\"></td>\n");
      out.write("\t\t\t\t<td><input id=\"remark\" type=\"text\" name=\"remark\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.remark}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input-small\"></td>\n");
      out.write("\t\t\t\t<td><a href=\"javascript:;\" onclick=\"deleteTrRow(this);\" data-toggle=\"tooltip\" title=\"删除\"><i class=\"glyphicon glyphicon-remove\"></i></a></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t</tbody>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<div class=\"toolbar\">\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-success dropdown-toggle\" onclick=\"addrow();\">\n");
      out.write("\t\t\t\t<span class=\"glyphicon glyphicon  glyphicon-plus\" aria-hidden=\"true\"></span>增加\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-info\" onclick=\"save()\">\n");
      out.write("\t\t\t\t<span class=\" glyphicon glyphicon-floppy-save\" aria-hidden=\"true\"></span>保存\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<a class=\"btn btn-warning\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/qy/basCostConfig/index\">\n");
      out.write("\t\t\t\t<span class=\" glyphicon glyphicon-arrow-left\" aria-hidden=\"true\"></span>返回\n");
      out.write("\t\t\t</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/inc/footer.jsp", out, true);
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t//动态新增一行\n");
      out.write("    function addrow(){\n");
      out.write("        var tables = $('#editable');\n");
      out.write("\n");
      out.write("        var addtr = $(\"<tr>\"+\n");
      out.write("            \"<td><input id='calcYf' type='text' name='calcYf' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.calcYf}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small form-control' style='width: 80px;'></td>\"+\n");
      out.write("            \"<td><input id='pdId' type='text' name='pdId' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.pdId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small' style='direction:rtl;width: 122px;padding: 0px'>\" +\n");
      out.write("            \t\"<a onclick='getRow(this);' href='javascript:;' title='获取' data-toggle='tooltip'><i class='glyphicon glyphicon-search'></i></a>\"+\n");
      out.write("\t\t\t\"</td>\"+\n");
      out.write("            \"<td id='orderId'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.orderId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\"+\n");
      out.write("            \"<td id='dcPrjId'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.dcPrjId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\"+\n");
      out.write("            \"<td id='dcPrjName' style='max-width: 100px;overflow:hidden;text-overflow:ellipsis;' nowrap class='title'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.dcPrjName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\"+\n");
      out.write("            \"<td id='costClassName' style='max-width: 90px;overflow:hidden;text-overflow:ellipsis;' nowrap class='title'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.costClassName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\"+\n");
      out.write("            \"<td><input id='finalMancost' type='text' name='finalMancost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalMancost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small'></td>\"+\n");
      out.write("            \"<td><input id='finalPmmancost' type='text' name='finalPmmancost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalPmmancost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small' style='width: 65px;'></td>\"+\n");
      out.write("            \"<td><input id='finalRiskabilitycost' type='text' name='finalRiskabilitycost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalRiskabilitycost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small' style='width: 65px;'></td>\"+\n");
      out.write("            \"<td><input id='finalUrgecost' type='text' name='finalUrgecost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalUrgecost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small' style='width: 65px;'></td>\"+\n");
      out.write("            \"<td><input id='finalSuburgecost' type='text' name='finalSuburgecost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalSuburgecost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small' style='width: 65px;'></td>\"+\n");
      out.write("            \"<td><input id='finalSubcost' type='text' name='finalSubcost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalSubcost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small'></td>\"+\n");
      out.write("            \"<td><input id='finalHostcost' type='text' name='finalHostcost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalHostcost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small'></td>\"+\n");
      out.write("            \"<td><input id='finalManurgecost' type='text' name='finalManurgecost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalManurgecost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small'></td>\"+\n");
      out.write("            \"<td><input id='finalHostmancost' type='text' name='finalHostmancost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalHostmancost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small'></td>\"+\n");
      out.write("            \"<td><input id='finalSubriskcost' type='text' name='finalSubriskcost' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.finalSubriskcost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small'></td>\"+\n");
      out.write("            \"<td><input id='payDate' type='text' name='payDate' value='");
      if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_page_context))
        return;
      out.write("' class='input-small form-control' style='width: 100px;'></td>\"+\n");
      out.write("            \"<td><input id='remark' type='text' name='remark' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.remark}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class='input-small'></td>\"+\n");
      out.write("            \"<td><a onclick='deleteTrRow(this);' data-toggle='tooltip' title='删除'><i class='glyphicon glyphicon-remove'></i></a></td>\"+\n");
      out.write("            \"</tr>\");\n");
      out.write("\n");
      out.write("        addtr.appendTo(tables);\n");
      out.write("        $(\"select\").select2();\n");
      out.write("\t\tdatetimepicker();\n");
      out.write("    }\n");
      out.write("\t//删除一行\n");
      out.write("    function deleteTrRow(tr){\n");
      out.write("\n");
      out.write("        //多一个parent就代表向前一个标签,\n");
      out.write("\n");
      out.write("        //本删除范围为<td><tr>两个标签,即向前两个parent\n");
      out.write("\n");
      out.write("        //如果多一个parent就会删除整个table\n");
      out.write("\n");
      out.write("        $(tr).parent().parent().remove();\n");
      out.write("\n");
      out.write("    }\n");
      out.write("    //获取\n");
      out.write("    function getRow(tr){\n");
      out.write("        var pdId = $(tr).prev().val();\n");
      out.write("\n");
      out.write("        var url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/qy/basCostConfig/search\";\n");
      out.write("        $.ajax({\n");
      out.write("            url: url,\n");
      out.write("            type: \"POST\",\n");
      out.write("            datatype:\"json\",\n");
      out.write("            contentType: \"application/json; charset=utf-8\",\n");
      out.write("            data: pdId,\n");
      out.write("            success : function(data, status){\n");
      out.write("                var orderId = $(tr).parent().next();\n");
      out.write("                orderId.text(data.orderId);\n");
      out.write("                orderId.next().text(data.dcPrjId);\n");
      out.write("                orderId.next().next().text(data.dcPrjName);\n");
      out.write("                orderId.next().next().next().text(data.costClassName);\n");
      out.write("                $(\".title\").each(function () {\n");
      out.write("                    $(this).attr(\"title\", $(this).text());\n");
      out.write("                })\n");
      out.write("                /*var costClassName = orderId.next().next().next().children().children();\n");
      out.write("                for (var i = 0, count = costClassName.length; i < count; i++) {\n");
      out.write("                    var option = costClassName[i].value;\n");
      out.write("                    var cos = data.costClassName;\n");
      out.write("                    if (costClassName[i].value == data.costClassName) {\n");
      out.write("                        costClassName[i].selected=true;\n");
      out.write("                        break;\n");
      out.write("                    }\n");
      out.write("                }*/\n");
      out.write("            },\n");
      out.write("            error : function() {\n");
      out.write("                alert(\"error\");\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    //保存\n");
      out.write("    function save(){\n");
      out.write("        /**\n");
      out.write("         * 遍历表格内容返回数组\n");
      out.write("         * @param Int  id 表格id\n");
      out.write("         * @return Array\n");
      out.write("         */\n");
      out.write("        var tableData = new Array();\n");
      out.write("        var flag = true;\n");
      out.write("        $(\"#editable tbody tr\").each(function(trindex,tritem){//遍历每一行\n");
      out.write("            var rowData = new Array();//存储每一行数据\n");
      out.write("            $(tritem).find(\"td\").each(function(tdindex,tditem){\n");
      out.write("                if($(tditem).find(\"input\").attr(\"name\")){\n");
      out.write("                    rowData.push('\"' + $(tditem).find(\"input\").attr(\"name\") + '\":\"' + $(tditem).find(\"input\").val() + '\"');//遍历每一个数据，并存入\n");
      out.write("\t\t\t\t}else{\n");
      out.write("                    if($(tditem).text()){\n");
      out.write("                        rowData.push('\"' + $(tditem).attr(\"id\") + '\":\"' + $(tditem).text() + '\"');//遍历每一个数据，并存入\n");
      out.write("\t\t\t\t\t}else if(!$(tditem).text() && !$(tditem).find(\"a\")){\n");
      out.write("                        flag = false;\n");
      out.write("                        alert(\"订单编号不能为空！\");\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            $(tritem).find(\"input\").each(function(tdindex,tditem){\n");
      out.write("                rowData.push('\"' + $(tditem).attr(\"name\") + '\":\"' + $(tditem).val() + '\"');//遍历每一个数据，并存入\n");
      out.write("            });\n");
      out.write("            tableData.push(\"{\" + rowData + \"}\");//将每一行的数据存入\n");
      out.write("        });\n");
      out.write("        tableData = \"[\" + tableData + \"]\";\n");
      out.write("\n");
      out.write("\t\tif(flag){\n");
      out.write("            var url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/qy/basCostConfig/create\";\n");
      out.write("            $.ajax({\n");
      out.write("                url: url,\n");
      out.write("                type: \"POST\",\n");
      out.write("                datatype:\"json\",\n");
      out.write("                contentType: \"application/json; charset=utf-8\",\n");
      out.write("                data: tableData,\n");
      out.write("                success : function(data, status){\n");
      out.write("                    window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/qy/basCostConfig/index\";\n");
      out.write("                },\n");
      out.write("                error : function() {\n");
      out.write("                    alert(\"error\");\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    $(function () {\n");
      out.write("\t\tdatetimepicker();\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    function datetimepicker() {\n");
      out.write("        //时间\n");
      out.write("        $(\"[id=calcYf]\").datetimepicker({\n");
      out.write("            language:  'zh-CN',\n");
      out.write("            format: 'yyyy-mm',\n");
      out.write("//\t\t\tstartDate: new Date(),\n");
      out.write("            startView: 3,//4:年 3：月 2：日 1：时 0：分\n");
      out.write("            minView: 3,//4:年 3：月 2：日 1：时 0：分\n");
      out.write("            weekStart: 1,\n");
      out.write("            autoclose:true,\n");
      out.write("\t\t\tautoUpdateTimeout: false,\n");
      out.write("            forceParse: true,\n");
      out.write("\t\t\tstartDate: new Date()\n");
      out.write("        });\n");
      out.write("        //时间\n");
      out.write("        $(\"[id=payDate]\").datetimepicker({\n");
      out.write("            language:  'zh-CN',\n");
      out.write("            format: 'yyyy-mm-dd',\n");
      out.write("            startView: 2,//4:年 3：月 2：日 1：时 0：分\n");
      out.write("            minView: 2,//4:年 3：月 2：日 1：时 0：分\n");
      out.write("            weekStart: 1,\n");
      out.write("            todayBtn: 1,//显示‘今日’按钮\n");
      out.write("            clearBtn:true,//清除按钮\n");
      out.write("            autoclose:true,\n");
      out.write("            forceParse: true,\n");
      out.write("\t\t\tstartDate: new Date(new Date().getFullYear(), new Date().getMonth(), 1)\n");
      out.write("        });\n");
      out.write("        $('[id=calcYf]').each(function(){\n");
      out.write("            var value = $(this).val();\n");
      out.write("            if(value.length == 6)\n");
      out.write("                $(this).val(value.substring(0, 4) + \"-\" + value.substring(4, 6));\n");
      out.write("        });\n");
      out.write("\n");
      out.write("    }\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/manage/qy/basCostConfigCreate.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("basePath");
      // /WEB-INF/jsp/manage/qy/basCostConfigCreate.jsp(9,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/jsp/manage/qy/basCostConfigCreate.jsp(67,62) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.payDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/manage/qy/basCostConfigCreate.jsp(67,62) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      // /WEB-INF/jsp/manage/qy/basCostConfigCreate.jsp(67,62) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setType("both");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent(null);
      // /WEB-INF/jsp/manage/qy/basCostConfigCreate.jsp(111,71) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basCostConfig.payDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/manage/qy/basCostConfigCreate.jsp(111,71) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy-MM-dd");
      // /WEB-INF/jsp/manage/qy/basCostConfigCreate.jsp(111,71) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setType("both");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }
}
