version: '3'
services:
    zoo1:
        image: 10.126.2.65:5000/zookeeper_cluster
#        restart: always
        hostname: zoo1
        volumes:
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - /etc/localtime:/etc/localtime:ro
#            - /home/zookeeper/zk1/data:/data
#            - /home/zookeeper/zk1/datalog:/datalog
        deploy:
            placement:
                constraints: [node.hostname == wbm65]
            resources:
                limits:
                    memory: 200M

    zoo2:
        image: 10.126.2.65:5000/zookeeper_cluster
#        restart: always
        hostname: zoo2
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - /etc/localtime:/etc/localtime:ro
#            - /home/zookeeper/zk2/data:/data
#            - /home/zookeeper/zk2/datalog:/datalog
        deploy:
            placement:
                constraints: [node.hostname == wbm65]
            resources:
                limits:
                    memory: 200M
    zoo3:
        image: 10.126.2.65:5000/zookeeper_cluster
#        restart: always
        hostname: zoo3
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - /etc/localtime:/etc/localtime:ro
#            - /home/zookeeper/zk3/data:/data
#            - /home/zookeeper/zk3/datalog:/datalog

        deploy:
            placement:
                constraints: [node.hostname == wbm65]
            resources:
                limits:
                    memory: 200M
