version: '3'
services:
    zoo1:
        image: 10.126.2.65:5000/zookeeper_cluster
        hostname: zoo1
        volumes:
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888
        volumes:
            - /etc/localtime:/etc/localtime:ro
        deploy:
            resources:
                limits:
                    memory: 200M

    zoo2:
        image: 10.126.2.65:5000/zookeeper_cluster
        hostname: zoo2
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888
        volumes:
            - /etc/localtime:/etc/localtime:ro
        deploy:
            resources:
                limits:
                    memory: 200M
